export const foodData = [
  {
    id: 1,
    name: "Hue Beef Noodle Soup",
    price: "50,000 VND",
    description: "A famous noodle dish with a rich and spicy flavor.",
    image: "https://res.cloudinary.com/dvxzmwuat/image/upload/v1740412414/td7ehpiezsf8a7rjy8qw.jpg",
    category: "Noodle Dishes",
  },
  {
    id: 2,
    name: "Broken Rice with Grilled Pork",
    price: "45,000 VND",
    description: "Delicious broken rice served with grilled pork and sweet-sour fish sauce.",
    image: "https://res.cloudinary.com/dvxzmwuat/image/upload/v1740412414/td7ehpiezsf8a7rjy8qw.jpg",
    category: "Rice Dishes",
  },
  {
    id: 3,
    name: "Beef Pho",
    price: "55,000 VND",
    description: "A fragrant beef noodle soup with flavorful broth and tender beef.",
    image: "https://res.cloudinary.com/dvxzmwuat/image/upload/v1740412414/td7ehpiezsf8a7rjy8qw.jpg",
    category: "Noodle Dishes",
  },
  {
    id: 4,
    name: "Fresh Spring Rolls",
    price: "30,000 VND",
    description: "A refreshing appetizer with shrimp, pork, fresh vegetables, and rice paper.",
    image: "https://res.cloudinary.com/dvxzmwuat/image/upload/v1740412414/td7ehpiezsf8a7rjy8qw.jpg",
    category: "Appetizers",
  },
  {
    id: 5,
    name: "Vietnamese Baguette Sandwich",
    price: "25,000 VND",
    description: "A Vietnamese-style sandwich with grilled meat, pâté, and fresh herbs.",
    image: "https://res.cloudinary.com/dvxzmwuat/image/upload/v1740412414/td7ehpiezsf8a7rjy8qw.jpg",
    category: "Fast Food",
  },
  {
    id: 6,
    name: "Hanoi Grilled Pork Vermicelli",
    price: "60,000 VND",
    description: "Traditional vermicelli with grilled pork and sweet-sour fish sauce.",
    image: "https://res.cloudinary.com/dvxzmwuat/image/upload/v1740412414/td7ehpiezsf8a7rjy8qw.jpg",
    category: "Noodle Dishes",
  },
  {
    id: 7,
    name: "Nam Vang Noodle Soup",
    price: "50,000 VND",
    description: "A rich noodle soup with shrimp, minced pork, and quail eggs.",
    image: "https://res.cloudinary.com/dvxzmwuat/image/upload/v1740412414/td7ehpiezsf8a7rjy8qw.jpg",
    category: "Noodle Dishes",
  },
  {
    id: 8,
    name: "Vietnamese Crispy Pancake",
    price: "40,000 VND",
    description: "Crispy pancake filled with shrimp, pork, bean sprouts, and served with fish sauce.",
    image: "https://res.cloudinary.com/dvxzmwuat/image/upload/v1740412414/td7ehpiezsf8a7rjy8qw.jpg",
    category: "Snacks",
  },
  {
    id: 9,
    name: "Fried Spring Rolls",
    price: "35,000 VND",
    description: "Crispy fried spring rolls filled with meat and vegetables.",
    image: "https://res.cloudinary.com/dvxzmwuat/image/upload/v1740412414/td7ehpiezsf8a7rjy8qw.jpg",
    category: "Appetizers",
  },
  {
    id: 10,
    name: "Spicy Thai Hotpot",
    price: "200,000 VND",
    description: "A spicy and sour Thai-style hotpot with seafood, mushrooms, and vegetables.",
    image: "https://res.cloudinary.com/dvxzmwuat/image/upload/v1740412414/td7ehpiezsf8a7rjy8qw.jpg",
    category: "Hotpot",
  },
  {
    id: 11,
    name: "Vietnamese Beef Stew",
    price: "65,000 VND",
    description: "Tender beef stew served with bread or noodles.",
    image: "https://res.cloudinary.com/dvxzmwuat/image/upload/v1740412414/td7ehpiezsf8a7rjy8qw.jpg",
    category: "Stewed Dishes",
  },
  {
    id: 12,
    name: "Honey Grilled Chicken",
    price: "90,000 VND",
    description: "Crispy honey-glazed grilled chicken with a sweet and savory taste.",
    image: "https://res.cloudinary.com/dvxzmwuat/image/upload/v1740412414/td7ehpiezsf8a7rjy8qw.jpg",
    category: "Grilled Dishes",
  },
  {
    id: 13,
    name: "Quang-style Noodles",
    price: "50,000 VND",
    description: "A flavorful noodle dish with shrimp, pork, eggs, and fresh vegetables.",
    image: "https://res.cloudinary.com/dvxzmwuat/image/upload/v1740412414/td7ehpiezsf8a7rjy8qw.jpg",
    category: "Noodle Dishes",
  },
  {
    id: 14,
    name: "Braised Fish in Clay Pot",
    price: "80,000 VND",
    description: "Delicious braised fish with black pepper and fish sauce.",
    image: "https://res.cloudinary.com/dvxzmwuat/image/upload/v1740412414/td7ehpiezsf8a7rjy8qw.jpg",
    category: "Braised Dishes",
  },
  {
    id: 15,
    name: "Grilled Pork Sausages",
    price: "55,000 VND",
    description: "Fragrant grilled pork sausages served with fresh vegetables and rice paper.",
    image: "https://res.cloudinary.com/dvxzmwuat/image/upload/v1740412414/td7ehpiezsf8a7rjy8qw.jpg",
    category: "Grilled Dishes",
  },
  {
    id: 16,
    name: "Steamed Savory Rice Cakes",
    price: "30,000 VND",
    description: "Soft rice cakes topped with dried shrimp and sweet-salty fish sauce.",
    image: "https://res.cloudinary.com/dvxzmwuat/image/upload/v1740412414/td7ehpiezsf8a7rjy8qw.jpg",
    category: "Snacks",
  },
  {
    id: 17,
    name: "Three-color Sweet Dessert",
    price: "25,000 VND",
    description: "A dessert with layers of mung beans, red beans, and jelly.",
    image: "https://res.cloudinary.com/dvxzmwuat/image/upload/v1740412414/td7ehpiezsf8a7rjy8qw.jpg",
    category: "Desserts",
  },
  {
    id: 18,
    name: "Bubble Milk Tea",
    price: "40,000 VND",
    description: "Delicious milk tea with chewy tapioca pearls.",
    image: "https://res.cloudinary.com/dvxzmwuat/image/upload/v1740412414/td7ehpiezsf8a7rjy8qw.jpg",
    category: "Beverages",
  }
];
