export const foodData = [
  {
    id: 1,
    name: "Bún Bò Huế",
    price: "50.000đ",
    description: "Món bún nổi tiếng với hương vị đậm đà và cay nồng.",
    image: "https://res.cloudinary.com/dvxzmwuat/image/upload/v1740412414/td7ehpiezsf8a7rjy8qw.jpg",
    category: "Món nước",
  },
  {
    id: 2,
    name: "Cơm Tấm Sườn",
    price: "45.000đ",
    description: "Cơm tấm ngon với sườn nướng và nước mắm chua ngọt.",
    image: "https://res.cloudinary.com/dvxzmwuat/image/upload/v1740412414/td7ehpiezsf8a7rjy8qw.jpg",
    category: "Món cơm",
  },
  {
    id: 3,
    name: "Phở Bò",
    price: "55.000đ",
    description: "Phở bò thơm ngon, nước dùng đậm đà, thịt bò mềm.",
    image: "https://res.cloudinary.com/dvxzmwuat/image/upload/v1740412414/td7ehpiezsf8a7rjy8qw.jpg",
    category: "Món nước",
  },
  {
    id: 4,
    name: "Gỏi Cuốn",
    price: "30.000đ",
    description: "Món khai vị tươi mát với tôm, thịt, rau sống và bánh tráng.",
    image: "https://res.cloudinary.com/dvxzmwuat/image/upload/v1740412414/td7ehpiezsf8a7rjy8qw.jpg",
    category: "Món khai vị",
  },
  {
    id: 5,
    name: "Bánh Mì Thịt",
    price: "25.000đ",
    description: "Bánh mì Việt Nam với thịt nướng, pate và rau thơm.",
    image: "https://res.cloudinary.com/dvxzmwuat/image/upload/v1740412414/td7ehpiezsf8a7rjy8qw.jpg",
    category: "Món ăn nhanh",
  },
  {
    id: 6,
    name: "Bún Chả Hà Nội",
    price: "60.000đ",
    description: "Bún chả truyền thống với thịt nướng, nước mắm chua ngọt.",
    image: "https://res.cloudinary.com/dvxzmwuat/image/upload/v1740412414/td7ehpiezsf8a7rjy8qw.jpg",
    category: "Món nước",
  },
  {
    id: 7,
    name: "Hủ Tiếu Nam Vang",
    price: "50.000đ",
    description: "Hủ tiếu nước hoặc khô với tôm, thịt bằm và trứng cút.",
    image: "https://res.cloudinary.com/dvxzmwuat/image/upload/v1740412414/td7ehpiezsf8a7rjy8qw.jpg",
    category: "Món nước",
  },
  {
    id: 8,
    name: "Bánh Xèo",
    price: "40.000đ",
    description: "Bánh xèo giòn rụm với nhân tôm, thịt, giá đỗ và nước mắm.",
    image: "https://res.cloudinary.com/dvxzmwuat/image/upload/v1740412414/td7ehpiezsf8a7rjy8qw.jpg",
    category: "Món ăn vặt",
  },
  {
    id: 9,
    name: "Chả Giò",
    price: "35.000đ",
    description: "Chả giò chiên giòn, nhân thịt và rau củ thơm ngon.",
    image: "https://res.cloudinary.com/dvxzmwuat/image/upload/v1740412414/td7ehpiezsf8a7rjy8qw.jpg",
    category: "Món khai vị",
  },
  {
    id: 10,
    name: "Lẩu Thái Chua Cay",
    price: "200.000đ",
    description: "Lẩu thái chua cay với hải sản, nấm và rau xanh.",
    image: "https://res.cloudinary.com/dvxzmwuat/image/upload/v1740412414/td7ehpiezsf8a7rjy8qw.jpg",
    category: "Món lẩu",
  },
  {
    id: 11,
    name: "Bò Kho",
    price: "65.000đ",
    description: "Bò kho hầm mềm, ăn kèm bánh mì hoặc bún.",
    image: "https://res.cloudinary.com/dvxzmwuat/image/upload/v1740412414/td7ehpiezsf8a7rjy8qw.jpg",
    category: "Món hầm",
  },
  {
    id: 12,
    name: "Gà Nướng Mật Ong",
    price: "90.000đ",
    description: "Gà nướng mật ong giòn rụm, vị ngọt thanh.",
    image: "https://res.cloudinary.com/dvxzmwuat/image/upload/v1740412414/td7ehpiezsf8a7rjy8qw.jpg",
    category: "Món nướng",
  },
  {
    id: 13,
    name: "Mì Quảng",
    price: "50.000đ",
    description: "Mì Quảng đậm đà với tôm, thịt, trứng và rau sống.",
    image: "https://res.cloudinary.com/dvxzmwuat/image/upload/v1740412414/td7ehpiezsf8a7rjy8qw.jpg",
    category: "Món nước",
  },
  {
    id: 14,
    name: "Cá Kho Tộ",
    price: "80.000đ",
    description: "Cá kho tộ thơm ngon, đậm vị với tiêu và nước mắm.",
    image: "https://res.cloudinary.com/dvxzmwuat/image/upload/v1740412414/td7ehpiezsf8a7rjy8qw.jpg",
    category: "Món kho",
  },
  {
    id: 15,
    name: "Nem Nướng",
    price: "55.000đ",
    description: "Nem nướng thơm lừng, ăn kèm rau sống và bánh tráng.",
    image: "https://res.cloudinary.com/dvxzmwuat/image/upload/v1740412414/td7ehpiezsf8a7rjy8qw.jpg",
    category: "Món nướng",
  },
  {
    id: 16,
    name: "Bánh Bèo",
    price: "30.000đ",
    description: "Bánh bèo mềm, topping tôm cháy, nước mắm mặn ngọt.",
    image: "https://res.cloudinary.com/dvxzmwuat/image/upload/v1740412414/td7ehpiezsf8a7rjy8qw.jpg",
    category: "Món ăn vặt",
  },
  {
    id: 17,
    name: "Chè Ba Màu",
    price: "25.000đ",
    description: "Chè ba màu với đậu xanh, đậu đỏ và rau câu.",
    image: "https://res.cloudinary.com/dvxzmwuat/image/upload/v1740412414/td7ehpiezsf8a7rjy8qw.jpg",
    category: "Món tráng miệng",
  },
  {
    id: 18,
    name: "Trà Sữa Trân Châu",
    price: "40.000đ",
    description: "Trà sữa thơm ngon với trân châu dai giòn.",
    image: "https://res.cloudinary.com/dvxzmwuat/image/upload/v1740412414/td7ehpiezsf8a7rjy8qw.jpg",
    category: "Đồ uống",
  }
];
